Добавлены файлы для страниц Волонтеры и О нас
Goncharova-Dasha/Prog_dev pull request #16
Opened 2024-12-06 11:56 UTC by Goncharova-Dasha

2024-12-09 06:57 UTC, nastbez approved these changes

2024-12-09 07:01 UTC, dmitrrieva approved these changes

2024-12-14 17:14 UTC, Laggon requested changes
Ответственным за задачу и PR должен быть один человек

Так как ведется работа над двумя страницами, возможно стоит разделить эти задачи

2024-12-14 17:14 UTC, Laggon commented on README.md
> +  [Файл style.css](style.css)
Добавлять ссылки на сами страницы не нужно, достаточно ссылки на главную страницу

Также уберите вторую ссылку на style.css

2024-12-14 17:23 UTC, Goncharova-Dasha commented on README.md
> +  [Файл style.css](style.css)
То есть нужно убрать ссылки на adout.html и volunteers.html?

2024-12-14 17:51 UTC, Laggon commented on README.md
> +  [Файл style.css](style.css)
Из `README.md` да. Из описания должна быть возможность перейти в сам сайт (index.html), а уже в нем есть ссылки на страницы для перемещения внутри сайта

2024-12-14 17:52 UTC, Laggon requested changes
Из `README.md` убрать ссылки на страницы, кроме главной. А также на служебные файлы (style.css)

2024-12-14 17:53 UTC, Goncharova-Dasha commented on README.md
> +  [Файл style.css](style.css)
исправила

2024-12-15 08:12 UTC, Laggon requested changes

2024-12-15 08:12 UTC, Laggon commented on README.md
> +  [Файл style.css](style.css)
Это служебный файл, который указывать не нужно. Он же подключен в самих страницах

2024-12-15 08:13 UTC, Laggon commented on README.md
> +  [Файл style.css](style.css)
В issue тоже нужно поправить

2024-12-16 06:55 UTC, Laggon approved these changes

2024-12-16 06:55 UTC, merged