Добавлена страница Котики
Goncharova-Dasha/Prog_dev pull request #19
Opened 2024-12-06 12:07 UTC by Goncharova-Dasha

2024-12-09 06:57 UTC, nastbez approved these changes

2024-12-09 07:01 UTC, dmitrrieva approved these changes

2024-12-14 16:57 UTC, Laggon requested changes
Нужно исправить отставание от основной ветки и конфликты

nit: Изображения стоит поместить в отдельную папку (например images)

2024-12-14 16:57 UTC, Laggon commented on README.md
> -- [Техническое задание](inf.md)
Нужно исправить отставание от основной ветки и убирать ссылку на ТЗ не нужно

2024-12-14 16:57 UTC, Laggon commented on README.md
> +  [Файл style.css](style.css)
Достаточно ссылки на основную страницу, на служебные файлы ссылки указывать не нужно

2024-12-16 07:00 UTC, Laggon requested changes
Не отображаются картинки

2024-12-16 07:38 UTC, Laggon approved these changes

2024-12-16 07:39 UTC, merged